# Generated by Django 2.2.11 on 2020-11-03 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('supporting_file', models.FileField(null=True, upload_to='help/articles/')),
            ],
            options={
                'db_table': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('supporting_file', models.FileField(null=True, upload_to='help/bugs/')),
            ],
            options={
                'db_table': 'Bugs',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_id', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('supporting_file', models.FileField(null=True, upload_to='partner/certificate/')),
            ],
            options={
                'db_table': 'Certificates',
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expiry_date', models.DateTimeField()),
                ('customer_id', models.CharField(max_length=15)),
                ('partner_id', models.CharField(max_length=15)),
                ('grand_total', models.FloatField()),
                ('status', models.CharField(choices=[('APL', 'Applied'), ('APR', 'Approved'), ('ORD', 'Ordered'), ('CLS', 'Closed'), ('EXT', 'Extended'), ('EXP', 'Expired'), ('MIN', 'More Info Needed')], max_length=2)),
                ('more_info', models.TextField(blank=True, null=True)),
                ('incentive', models.CharField(choices=[('A', 'Type A'), ('B', 'Type B')], max_length=2)),
                ('discount', models.FloatField()),
            ],
            options={
                'db_table': 'Deals',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15)),
                ('customer_id', models.CharField(max_length=15)),
                ('partner_id', models.CharField(max_length=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supporting_file', models.FileField(null=True, upload_to='customer/invoices/')),
            ],
            options={
                'db_table': 'Invoices',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_id', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('renewed_ad', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField(auto_now_add=True)),
                ('auto_renew', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partner/logo/')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=25)),
                ('address', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Partners',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=30)),
                ('monthly_basic_price', models.FloatField()),
                ('monthly_professional_price', models.FloatField()),
                ('yearly_basic_price', models.FloatField()),
                ('yearly_professional_price', models.FloatField()),
            ],
            options={
                'db_table': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quotation_id', models.CharField(max_length=15)),
                ('customer_id', models.CharField(max_length=15)),
                ('partner_id', models.CharField(max_length=15)),
                ('grand_total', models.FloatField()),
                ('status', models.CharField(choices=[('OR', 'Ordered'), ('OP', 'Open')], max_length=2)),
                ('file', models.FileField(null=True, upload_to='partner/quotation/')),
            ],
            options={
                'db_table': 'Quotations',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_id', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('supporting_file', models.FileField(null=True, upload_to='partner/training/')),
            ],
            options={
                'db_table': 'Trainings',
            },
        ),
        migrations.CreateModel(
            name='UserCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=15)),
                ('card_number', models.CharField(blank=True, max_length=4, null=True)),
                ('name_on_card', models.CharField(blank=True, max_length=30, null=True)),
                ('expiry', models.CharField(blank=True, max_length=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'UserCredits',
            },
        ),
        migrations.CreateModel(
            name='QuotationProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types_of_licenses', models.CharField(choices=[('F', 'Free'), ('B', 'Basic'), ('P', 'Professional')], max_length=1)),
                ('term_of_licenses', models.CharField(choices=[('M', 'Monthly'), ('Y', 'Yearly')], max_length=1)),
                ('quantity', models.IntegerField(default=1)),
                ('list_price', models.FloatField()),
                ('net_price', models.FloatField()),
                ('deal', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealproduct_deal', to='wmdc_admin.Deal')),
                ('part_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_product', to='wmdc_admin.Product')),
                ('quotation', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealproduct_quotation', to='wmdc_admin.Quotation')),
            ],
            options={
                'db_table': 'Quotation_Products',
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='quotation',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_quotation', to='wmdc_admin.Quotation'),
        ),
    ]
