# Generated by Django 2.2.11 on 2020-11-03 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wmdc_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='license',
            table='Licenses',
        ),
    ]
