# Generated by Django 2.2.11 on 2020-11-03 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wmdc_admin', '0002_auto_20201103_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='license',
            old_name='renewed_ad',
            new_name='renewed_at',
        ),
    ]
